receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "http://tempo:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
